# Discord Bot Core
# This file must be placed in the same folder as where you run `npm start` or `node .` (for ./dist)

devGuild: "964517482708758538"
botId: "958395272034152478"
tofuId: "792827809797898240"

numMarket: 50

# Duration in minutes
auctionDuration: 300
marketDuration: 1500

# =====================================
# =           STYLE OPTIONS           =
# =====================================

embeds:
  primary:
    color: "#548CFF"
  fail:
    color: "#F14A16"
  success:
    color: "#00FF00"